<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clase 16 Curso JS Mircha - Manejo de Errores</title>
</head>

<body>
    <script>

        //Bloque try-catch-finally
        try {
            console.log("En el Try metemos el código a evaluar");
            noExiste;
            console.log("Segundo mensaje en el Try");

        } catch (error) {
            console.log("Catch captura cualquier error surgido o lanzado en el Try");
            console.log(error);
        } finally {
            console.log("El bloque finally se ejecutará siempre al final de un bloque Try-catch, haya o no haya error");
        }

        try {
            let numero = "hola ";
            if (isNaN(numero)) {
                throw new Error("Esto no es un número")
            }
            console.log(numero * numero);
        } catch (error) {
            console.log(`Se produjo el siguiente error: ${error}`);
        }
    </script>
</body>

</html>